### ISSUE TITLE
Use folders like OE-A

### ISSUE THREAD

**Issue by AbuBaniaz** [PLi-metas/extra_rc_models#3]
Is it possible that we can use folders like how they are used on OE-A branding?

This will allow for for situations where one remote is used for many devices

**Comment by persianpros** [comment]
It's not important to use folder structure like OE-A but we can use a remote for multiple boxes in https://github.com/PLi-metas/extra_rc_models/blob/master/webif/owibranding.py and I think you forgot to add your remotes there ...

Also don't forget to change folders in html remotes which I just did it for you ;)

**Comment by AbuBaniaz** [comment]
Can you explain why the remote is not showing in openwebif please?

I have added the following locally to `owibranding.py` for now
```
		if (procmodel.startswith("tm")):
			brand = "Technomate"
			if procmodel == "tmnanosem2":
				model = procmodel.replace("tmnanosem2", "TM Nano SE M2")
```

**Comment by AbuBaniaz** [comment]
Please ignore last comment

```
	elif procmodel in ("tmnanosem2", "tmnanosem2plus"):
		remote = "tmnanosem2"
```
